stages:
  - sync

sync_to_github:
  stage: sync
  only:
    - main    # 或者指定你想要同步的分支
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.name "MindLocalize"
    - git config --global user.email "taozi@mindoffice.net"
    - git remote add github https://MindLocalize:${GITHUB_TOKEN}@github.com/MindLocalize//sdk-ios-demo.git
    - git push -f github HEAD:main